RULE_CF = {
    "lifestyle": 0.90,
    "budget": 0.85,
    "climate": 0.80,
    "duration": 0.70,
}
ADVISORY_RULES = [
    {"id": "conflict_budget", "priority": 6, "if": ["budget:Budget", "budget:Luxury"], "then": "conflict:budget", "message": "You mentioned both cheap and luxury - those pull apart, so I'll lean toward mid-range as a bridge."},
    {"id": "assume_midrange", "priority": 3, "if": ["conflict:budget"], "then": "action:assume_midrange", "message": "(I'll treat your budget as flexible / mid-range while ranking.)"},
    {"id": "daytrip_multi", "priority": 6, "if": ["duration:Day trip", "regions:multiple"], "then": "warn:daytrip_multi", "message": "A single day trip across several continents isn't realistic - one region would make more sense."},
    {"id": "beach_cold", "priority": 5, "if": ["wants:beaches", "climate:cold"], "then": "tension:beach_cold", "message": "Beaches usually shine in warm places - in a cold climate good beach matches may be few."},
    {"id": "night_seclusion", "priority": 5, "if": ["wants:nightlife", "wants:seclusion"], "then": "tension:night_seclusion", "message": "Lively nightlife and deep seclusion pull in opposite directions - I'll try to balance them."},
    {"id": "night_wellness", "priority": 4, "if": ["wants:nightlife", "wants:wellness"], "then": "tension:night_wellness", "message": "Partying and wellness/relaxation are a bit at odds - expect a compromise."},
    {"id": "urban_seclusion", "priority": 5, "if": ["wants:urban", "wants:seclusion"], "then": "tension:urban_seclusion", "message": "A buzzing city and quiet seclusion rarely live in the same place - I'll find a middle ground."},
    {"id": "urban_nature", "priority": 4, "if": ["wants:urban", "wants:nature"], "then": "tension:urban_nature", "message": "Big-city life and untouched nature can conflict - I'll favour places that blend both."},
    {"id": "adventure_wellness", "priority": 4, "if": ["wants:adventure", "wants:wellness"], "then": "tension:adventure_wellness", "message": "Adventure and pure relaxation are different moods - I'll balance energetic and calm options."},
    {"id": "luxury_budgetdest", "priority": 5, "if": ["budget:Luxury", "climate:cold", "wants:beaches"], "then": "tension:lux_cold_beach", "message": "Luxury cold-climate beaches are a very narrow niche - results may be sparse."},
    {"id": "beach_warm", "priority": 2, "if": ["wants:beaches", "climate:warm"], "then": "synergy:beach_warm", "message": "Nice - warm beach destinations are a classic sweet spot, so expect strong matches."},
    {"id": "culture_cuisine", "priority": 2, "if": ["wants:culture", "wants:cuisine"], "then": "synergy:culture_cuisine", "message": "Culture and cuisine pair beautifully - many cities excel at both."},
    {"id": "nature_adventure", "priority": 2, "if": ["wants:nature", "wants:adventure"], "then": "synergy:nature_adventure", "message": "Nature and adventure go hand in hand - lots of great fits for that."},
    {"id": "nightlife_urban_avoided", "priority": 4, "if": ["avoids:nightlife", "wants:urban"], "then": "tension:nightlife_urban", "message": "Urban destinations often have active nightlife — some of what you want to avoid may still appear in the results."},
    {"id": "winter_beaches", "priority": 5, "if": ["travel:winter", "wants:beaches"], "then": "tension:winter_beach", "message": "Winter travel and beach holidays often clash — consider tropical or southern-hemisphere destinations where winter is their summer."},
    {"id": "budget_luxury_exclude_conflict", "priority": 6, "if": ["budget:Luxury", "has:exclusions"], "then": "note:luxury_with_exclusions", "message": "You asked for luxury but also have active exclusions — results may be limited in this niche."},
    {"id": "results_broadened", "priority": 7, "if": ["results:broadened"], "then": "note:broadened", "message": "No destination matched your exact region, so I widened the search (still respecting any region you excluded)."},
    {"id": "results_empty", "priority": 7, "if": ["results:empty"], "then": "note:empty", "message": "I couldn't find anything matching all of that - try relaxing one wish (a region, the budget, or the climate)."},
    {"id": "results_weak", "priority": 4, "if": ["results:weak"], "then": "note:weak", "message": "These are the closest I found, but the matches are weak - loosening a criterion would help."},
    {"id": "results_contain_avoided", "priority": 5, "if": ["results:contain_avoided"], "then": "warn:avoided_in_results", "message": "Some recommended places score on features you wanted to avoid — exclusions are soft evidence, not hard filters. Say 'restart' to start fresh with tighter constraints."},
    {"id": "results_weak_exclusions", "priority": 4, "if": ["results:weak", "has:exclusions"], "then": "note:relax_exclusions", "message": "Matches are weak and you have active exclusions — relaxing some of them might open up better options."},
]
